packages/website-frontend/src/app/repository/modal/modal.component.spec.ts, packages/website-frontend/src/app/repository/modal/modal.component.ts
=> Fix badge link

packages/common/package.json, packages/data-access/package-lock.json, packages/data-access/package.json, packages/e2e/package-lock.json, packages/e2e/package.json, packages/website-backend/package-lock.json, packages/website-backend/package.json, packages/website-contract/package-lock.json, packages/website-contract/package.json, packages/website-frontend/package-lock.json, packages/website-frontend/package.json, packages/website-frontend/src/app/report/report-page/report-page.component.scss, packages/website-frontend/src/index.html
Offset the sticky file list legenda so that it is displayed when you scroll.
Fixes #133
=> feat(report): sticky file list legenda

.github/workflows/ci.yml, .github/workflows/e2e.yml, package-lock.json, package.json, packages/e2e/protractor.conf.ts, packages/website-backend/src/api/auth/GithubAuth.ts, tasks/webdriver-manager-update.js
=> Remove access to repository from required scopes

packages/common/package-lock.json, packages/common/package.json, packages/data-access/package-lock.json, packages/data-access/package.json, packages/e2e/package-lock.json, packages/e2e/package.json, packages/website-backend/package-lock.json, packages/website-backend/package.json, packages/website-contract/package-lock.json, packages/website-contract/package.json, packages/website-frontend/package-lock.json, packages/website-frontend/package.json
fix stryker-mutator/stryker-net#2510
=> fix(mte): allow valid mutant schema v2 reports

.editorconfig, .prettierrc, package.json, packages/stryker-elements/.prettierrc, packages/stryker-elements/package.json
=> style: stryker elements eslint linting

package.json, packages/e2e/spec/homepage.spec.ts, packages/stryker-elements/src/components/button.ts, packages/stryker-elements/src/components/common/progress-bar.ts, packages/stryker-elements/src/components/getting-started/getting-started-step-overview.ts, packages/stryker-elements/src/components/hero-component.ts, packages/stryker-elements/src/components/profile-button.ts, packages/stryker-elements/src/components/sign-in-button.ts, packages/stryker-elements/src/components/status-box-component.ts
=> refactor(stryker-elements): use lit directives

packages/stryker-elements/index.html, packages/stryker-elements/src/exports/lib/organisms/status-overview.ts, packages/stryker-elements/src/exports/lib/organisms/stryker-dashboard-explanation.ts, packages/stryker-elements/src/lib/organisms/hero.ts, packages/stryker-elements/src/lib/organisms/stryker-dashboard-explanation.ts, packages/stryker-elements/src/main.ts, packages/website-frontend/src/app/welcome/welcome.component.html
=> fix(website-frontend): add explanation to homepage

docker/Dockerfile, package-lock.json, packages/badge-api/.npmignore, packages/data-access/.npmignore, packages/website-backend/.npmignore, packages/website-backend/bin/healthcheck.js, packages/website-backend/package.json, packages/website-backend/src/app.module.ts, start-server.sh, tasks/download-badge-api-package.sh
build: use docker node-alpine image
=> fix: add healthcheck to docker image

packages/website-backend/src/services/real-time/MutationEventResponseHandler.ts, packages/website-backend/src/services/real-time/MutationEventSender.ts, packages/website-backend/test/tsconfig.json, packages/website-backend/test/unit/controllers/real-time-reports.controller.spec.ts, packages/website-backend/test/unit/helpers.ts, packages/website-backend/test/unit/services/real-time/MutationEventResponseHandler.spec.ts, packages/website-backend/test/unit/services/real-time/MutationEventSender.spec.ts
Fixes #592
This fixes the issue with compression
=> fix: send `.flush` after every real-time event

packages/e2e/.env.template, packages/e2e/.vscode/launch.json, packages/e2e/README.md, packages/e2e/actions/auth.action.ts, packages/e2e/actions/helpers.action.ts, packages/e2e/po/repositories/repositories-page.po.ts, packages/website-frontend/proxy.config.json
Improved our workflow slightly and added a readme on how to run E2E tests.
closes #550
=> docs(e2e): improve documentation of end to end testing

README.md, packages/e2e/README.md
=> docs: update outdated instructions in README.md

.github/workflows/deploy.yml, .github/workflows/e2e.yml
Allows you to click to the environment url
=> chore: add url to deployment environments

packages/website-frontend/src/pages/auth.page.ts, packages/website-frontend/test/unit/pages/auth.page.spec.ts
=> fix(website-frontend): redirect to repositories page after logging in

packages/website-frontend/src/pages/repositories.page.ts, packages/website-frontend/src/services/auth.service.ts, packages/website-frontend/src/services/history.service.ts, packages/website-frontend/test/unit/pages/repositories.page.spec.ts, packages/website-frontend/test/unit/services/auth.service.spec.ts, packages/website-frontend/test/unit/services/history.service.spec.ts, packages/website-frontend/test/unit/services/location.service.spec.ts
=> fix(website-frontend): switching org not reflected in URL

.github/workflows/renew-cert.yml
=> chore: renew certs automatically

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/e2e.yml, .github/workflows/mutation-testing.yml
=> chore: use federated credentials for deploying to production and acceptance

packages/website-frontend/src/pages/repositories.page.ts
=> fix(website-frontend): copy badge producing broken links

package-lock.json, packages/website-backend/package.json, packages/website-backend/src/index.ts, packages/website-backend/src/logger.ts, packages/website-backend/src/services/ReportValidator.ts, packages/website-frontend/package.json
There was not enough time to validate the report, now there is (but there is still a limit).
Related to #1183 
Also generates more logging to see what is going wrong, I am not sure why this wasn't done in the first place.
=> fix(website-backend): increase worker pool timeout

package-lock.json, packages/stryker-elements/package.json, packages/stryker-elements/src/lib/atoms/buttons/toggle-button.ts, packages/stryker-elements/src/lib/organisms/hero.ts, packages/stryker-elements/src/lib/organisms/status-overview.ts, packages/website-frontend/package.json
Caused issues with our styling, more investigation is needed (see #1288)
=> fix(website-frontend): revert tailwind version bump

package-lock.json, packages/stryker-elements/package.json, packages/stryker-elements/src/lib/atoms/buttons/toggle-button.ts, packages/stryker-elements/src/lib/organisms/hero.ts, packages/stryker-elements/src/lib/organisms/status-overview.ts, packages/stryker-elements/src/tailwind-styles/component.css, packages/website-frontend/package.json, packages/website-frontend/src/main.css, workspace.code-workspace
- **chore(deps): update tailwindcss and add stryker-elements to source detection**
- **Formatting**
=> chore(deps): update tailwindcss and add stryker-elements to source detection

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/e2e.yml
- **chore: remove --with-deps from playwright install**
- **chore: move some steps around**
=> chore: remove--with-deps from playwright install
